const state={audience:'school',mood:'',journal:'',goals:[]};
const programs={school:[['01','Growing Through School','Classes 1–8','Emotions, friendships, routines and self-understanding.'],['02','Exam & Study Wellbeing','Classes 6–12','Pressure, focus, routines, confidence and healthy study habits.'],['03','Senior School Balance','Classes 9–12','Expectations, exams, comparison and practical next steps.'],['04','School Wellbeing Toolkit','Institution','Campaigns, educator activities and aggregate insights.']],college:[['01','College Transition','Year 1','Adjustment, belonging, routines and finding support.'],['02','Academic Pressure','Year 1–4','Study load, procrastination, focus and sustainable routines.'],['03','Placement & Career Pressure','Year 3–PG','Interviews, uncertainty, comparison and practical next steps.'],['04','Campus Wellbeing Toolkit','Institution','Campaigns, programs and aggregate insights.']]};
function appHome(){return `<div class="app-kicker">${state.audience==='school'?'SCHOOL · CLASSES 6–12':'COLLEGE · YEAR 1–4'}</div><h3>Your space to feel, reflect & move forward.</h3><p>A private set of tools for everyday student life. Choose what feels useful today.</p><div class="app-cards"><div class="app-card"><span>♡</span><b>How are you today?</b><p>${state.mood?`You chose “${state.mood}”. You can change it anytime.`:'No judgement. No score.'}</p><button onclick="activateTab('checkin')">Start check-in →</button></div><div class="app-card"><span>✦</span><b>Recommended</b><p>Take 6 minutes to reset study pressure and choose one controllable next step.</p><button onclick="activateTab('exercise')">Start exercise →</button></div><div class="app-card"><span>✎</span><b>Private journal</b><p>Put down what is on your mind. Your writing stays in your private space.</p><button onclick="activateTab('journal')">Write privately →</button></div><div class="app-card"><span>◎</span><b>One small goal</b><p>Keep one meaningful thing moving instead of trying to fix everything at once.</p><button onclick="activateTab('goals')">Set a goal →</button></div></div>`}
function checkin(){return `<div class="app-kicker">DAILY CHECK-IN</div><h3>How are you feeling?</h3><p>Pick what fits right now. This is not a clinical assessment.</p><div class="moods">${['Good','Okay','Low','Stressed','Tired'].map(x=>`<button class="${state.mood===x?'chosen':''}" onclick="setMood('${x}')">${x}</button>`).join('')}</div><div style="margin-top:30px"><b>Stress</b><input style="width:100%;margin:16px 0" type="range" min="0" max="10" value="5" id="stressRange"><button class="primary" onclick="saveCheckin()">Save privately →</button></div>`}
function journal(){return `<div class="app-kicker">PRIVATE JOURNAL</div><h3>Write it down.</h3><p>School, college, friendships, family, pressure or goals — this is your space.</p><textarea id="journalText" style="width:100%;min-height:190px;padding:16px;border:1px solid #dfe3dc;border-radius:14px" placeholder="Right now I feel…">${state.journal}</textarea><br><button class="primary" onclick="saveJournal()">Save privately</button>`}
function exercise(){return `<div class="app-kicker">GUIDED EXERCISE</div><h3>Reset study pressure.</h3><p><b>6 minutes</b> · Study stress</p><div class="app-card"><b>Step 1 of 3</b><p>Name the part of the situation you can actually influence today. Write one sentence.</p><textarea id="ex" style="width:100%;min-height:100px;padding:12px;border:1px solid #dfe3dc;border-radius:10px" placeholder="I can control…"></textarea><button class="primary" onclick="finishExercise()">Continue →</button></div>`}
function goals(){return `<div class="app-kicker">MY GOALS</div><h3>Keep one thing moving.</h3><p>Start small enough to act on today.</p><input id="goalInput" style="width:100%;padding:14px;border:1px solid #dfe3dc;border-radius:10px" placeholder="e.g. Complete one focused study block"><button class="primary" style="margin-top:12px" onclick="saveGoal()">Add goal →</button>${state.goals.map(g=>`<div class="app-card" style="margin-top:12px"><b>ACTIVE GOAL</b><p>${escapeHtml(g)}</p></div>`).join('')}`}
function appPrograms(){return `<div class="app-kicker">PROGRAMS</div><h3>Structured support for your stage.</h3><p>Short pathways combine lessons, activities and reflection.</p><div class="app-cards">${programs[state.audience].map(p=>`<div class="app-card"><small>${p[1]}</small><b>${p[2]}</b><p>${p[3]}</p><button onclick="toast('Program preview opened')">Preview pathway →</button></div>`).join('')}</div>`}
function progress(){return `<div class="app-kicker">MY PROGRESS</div><h3>Notice patterns, not scores.</h3><p>Track actions and reflection. AAVYA does not diagnose or rank mental health.</p><div class="app-cards"><div class="app-card"><b>8</b><p>check-ins</p></div><div class="app-card"><b>${state.journal?'1':'0'}</b><p>journal entries</p></div><div class="app-card"><b>${state.goals.length}</b><p>goals started</p></div><div class="app-card"><b>6</b><p>exercises available</p></div></div>`}
function render(tab='home'){const map={home:appHome,checkin,journal,exercise,goals,programs:appPrograms,progress};document.getElementById('appContent').innerHTML=map[tab]();document.querySelectorAll('.tab').forEach(b=>b.classList.toggle('active',b.dataset.tab===tab))}
function activateTab(t){render(t);document.getElementById('student-app').scrollIntoView({behavior:'smooth'})}
function setAudience(a,el){state.audience=a;document.querySelectorAll('.audience-card').forEach(x=>x.classList.remove('active'));el.classList.add('active');render('home');renderPrograms()}
function setMood(x){state.mood=x;render('checkin');toast('Check-in updated privately')}
function saveCheckin(){toast('Check-in saved privately');render('home')}
function saveJournal(){state.journal=document.getElementById('journalText').value.trim();toast('Journal saved privately');render('journal')}
function saveGoal(){const v=document.getElementById('goalInput').value.trim();if(v){state.goals.unshift(v);toast('Goal added');render('goals')}}
function finishExercise(){toast('Exercise completed');render('home')}
function renderPrograms(){document.getElementById('programGrid').innerHTML=programs[state.audience].map(p=>`<article class="program"><span class="num">${p[0]}</span><h3>${p[1]}</h3><p><b>${p[2]}</b></p><p>${p[3]}</p></article>`).join('')}
function quickMood(btn,m){document.querySelectorAll('.moods button').forEach(x=>x.classList.remove('chosen'));btn.classList.add('chosen');state.mood=m;toast(`Feeling set to ${m}`)}
function openDemo(){document.getElementById('demoModal').classList.remove('hidden');document.body.style.overflow='hidden'}
function closeDemo(){document.getElementById('demoModal').classList.add('hidden');document.body.style.overflow=''}
function submitDemo(e){e.preventDefault();closeDemo();toast('Demo enquiry captured — connect your email/CRM before launch')}
function toast(t){let x=document.querySelector('.toast');if(!x){x=document.createElement('div');x.className='toast';document.body.appendChild(x)}x.textContent=t;setTimeout(()=>x.remove(),2200)}
function toggleMenu(){document.querySelector('.nav nav').classList.toggle('open')}
function showApp(){document.getElementById('student-app').scrollIntoView({behavior:'smooth'});render('home')}
function escapeHtml(s){return s.replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))}
document.querySelectorAll('.tab').forEach(b=>b.addEventListener('click',()=>render(b.dataset.tab)));render();renderPrograms();
