"use client";
import {useState} from "react";
import {Activity,BarChart3,BookOpen,BriefcaseBusiness,Check,ChevronRight,ClipboardList,GraduationCap,HeartHandshake,Home,LockKeyhole,Menu,MessageCircleHeart,Sparkles,Target,Users} from "lucide-react";

type Segment="School"|"College"|"Workplace";
type View="home"|"checkin"|"journal"|"goals"|"exercises"|"programs"|"progress"|"ai"|"support"|"privacy";
const exercises=[
 ["🎯","Pressure → Plan","Stress","8 min","Turn pressure into one controllable next step."],
 ["🧠","Thought Check","Reflection","6 min","Separate facts, assumptions and predictions."],
 ["⚡","Focus Reset","Focus","5 min","Create one realistic focus block."],
 ["🌿","Grounding Reset","Calm","4 min","A short sensory grounding activity."],
 ["🌙","Sleep Wind-down","Recovery","7 min","Build a calmer evening routine."],
 ["🤝","Support Map","Connection","10 min","Identify people and places you can reach."]
];
const programs=[["School Pressure Toolkit","Classes 6–12","6 weeks"],["College Transition","Year 1–PG","4 weeks"],["Placement Wellbeing","Year 3–4","6 weeks"],["Workday Wellbeing","Employees","4 weeks"]];

export default function Page(){
 const [segment,setSegment]=useState<Segment>("School"); const [view,setView]=useState<View>("home"); const [menu,setMenu]=useState(false);
 const [mood,setMood]=useState(""); const [stress,setStress]=useState(5); const [journal,setJournal]=useState(""); const [entries,setEntries]=useState<string[]>([]);
 const [goal,setGoal]=useState(""); const [goals,setGoals]=useState<string[]>([]); const [active,setActive]=useState<number|null>(null); const [step,setStep]=useState(0);
 const [messages,setMessages]=useState([{role:"ai",text:"Hi, I’m AAVYA. I can help you reflect, plan a small next step, or choose an exercise."}]); const [input,setInput]=useState("");
 const [toast,setToast]=useState("");
 const go=(v:View)=>{setView(v);setMenu(false);window.scrollTo({top:0,behavior:"smooth"})};
 const notify=(s:string)=>{setToast(s);window.setTimeout(()=>setToast(""),1800)};
 const nav:[[View,string,any],...any[]]=[["home","MySpace",Home],["checkin","Check-in",Activity],["journal","Journal",BookOpen],["goals","Goals",Target],["exercises","Exercises",Sparkles],["programs","Programs",ClipboardList],["progress","Progress",BarChart3],["ai","AAVYA AI",MessageCircleHeart],["support","Support",HeartHandshake]];
 return <main>
  {toast&&<div className="toast"><Check size={15}/>{toast}</div>}
  <header><button className="brand" onClick={()=>go("home")}><b>A</b><span><strong>AAVYA</strong><small>wellbeing, built around people</small></span></button>
   <div className="segments">{(["School","College","Workplace"] as Segment[]).map(x=><button className={segment===x?"active":""} key={x} onClick={()=>{setSegment(x);notify(`${x} experience selected`)}}>{x}</button>)}</div>
   <button className="menub" onClick={()=>setMenu(!menu)}><Menu/></button><div className="avatar">A</div>
  </header>
  <div className="layout"><aside className={menu?"open":""}><div className="context"><span>{segment[0]}</span><div><b>{segment}</b><small>{segment==="School"?"Classes 1–12":segment==="College"?"Year 1–PG":"Teams & HR"}</small></div></div><nav>{nav.map(([id,label,Icon])=><button key={id} className={view===id?"sel":""} onClick={()=>go(id)}><Icon size={17}/>{label}</button>)}</nav><div className="asidebottom"><button onClick={()=>go("privacy")}><LockKeyhole size={16}/>Privacy & data</button><p><LockKeyhole size={13}/> Personal space is separate from institution reporting.</p></div></aside>
   <section className="content"><div className="mobilebar"><b>{segment}</b><button onClick={()=>setMenu(true)}>Menu</button></div>
    {view==="home"&&<HomeView segment={segment} mood={mood} setMood={setMood} stress={stress} setStress={setStress} go={go}/>} 
    {view==="checkin"&&<Checkin mood={mood} setMood={setMood} stress={stress} setStress={setStress} save={()=>{notify("Check-in saved");go("home")}}/>}
    {view==="journal"&&<Journal value={journal} setValue={setJournal} entries={entries} save={()=>{if(journal.trim()){setEntries([journal.trim(),...entries]);setJournal("");notify("Journal saved privately")}}}/>} 
    {view==="goals"&&<Goals value={goal} setValue={setGoal} goals={goals} add={()=>{if(goal.trim()){setGoals([goal.trim(),...goals]);setGoal("");notify("Goal added")}}}/>} 
    {view==="exercises"&&<Exercises active={active} setActive={setActive} step={step} setStep={setStep} done={()=>{notify("Exercise completed");setActive(null);setStep(0)}}/>}
    {view==="programs"&&<Programs segment={segment} notify={notify}/>} {view==="progress"&&<Progress/>}
    {view==="ai"&&<AI messages={messages} input={input} setInput={setInput} send={()=>{if(!input.trim())return;const q=input.trim();setInput("");const answer=q.toLowerCase().includes("exam")?"Pick one subject, one 20-minute block and one clear definition of done.":q.toLowerCase().includes("stress")?"Try a short reset, then choose the one thing you can control right now.":"I can help you reflect, plan and choose a small next step.";setMessages([...messages,{role:"user",text:q},{role:"ai",text:answer}])}}/>}
    {view==="support"&&<Support segment={segment}/>} {view==="privacy"&&<Privacy/>}
    <footer>© AAVYA <span>Private by design</span><span>Support, not a replacement for professional care</span></footer>
   </section>
  </div>
 </main>
}
function Title({ey,title,sub}:{ey:string,title:string,sub:string}){return <div className="title"><small>{ey}</small><h1>{title}</h1><p>{sub}</p></div>}
function HomeView({segment,mood,setMood,stress,setStress,go}:any){return <div className="page"><div className="hero"><div><small>PERSONAL SPACE • TODAY</small><h1>Good morning, Ankit.</h1><p>A small step is still progress. Let’s make today’s next step useful.</p></div><div className="orb"><Sparkles/><b>Personalized<br/>for you</b></div></div>
 <div className="card check"><div className="head"><div><small>QUICK CHECK-IN</small><h2>How are you feeling right now?</h2></div><button onClick={()=>go("checkin")}>Full check-in →</button></div><div className="moods">{["Good","Okay","Low","Stressed","Tired"].map(x=><button key={x} className={mood===x?"chosen":""} onClick={()=>setMood(x)}>{x}</button>)}</div><div className="range"><span>Stress</span><input type="range" min="0" max="10" value={stress} onChange={e=>setStress(+e.target.value)}/><b>{stress}/10</b></div></div>
 <div className="section"><small>YOUR NEXT STEP</small><h2>Something you can do now</h2></div><div className="next"><div className="recommend"><span>🎯</span><div><em>RECOMMENDED</em><h2>{segment==="School"?"Exam pressure reset":segment==="College"?"Placement pressure reset":"Workload reset"}</h2><p>Turn pressure into one manageable action instead of trying to solve everything at once.</p><button onClick={()=>go("exercises")}>Start 8 min <ChevronRight size={15}/></button></div></div><div className="quick"><Action t="Your goals" s="Keep one thing moving." icon={<Target/>} go={()=>go("goals")}/><Action t="Private journal" s="Write without performing." icon={<BookOpen/>} go={()=>go("journal")}/><Action t="Talk to AAVYA" s="Reflect or plan." icon={<MessageCircleHeart/>} go={()=>go("ai")}/></div></div>
 <div className="section"><small>CONTINUE</small><h2>Built for your {segment.toLowerCase()} experience</h2></div><div className="tiles"><Tile t={segment==="School"?"School Pressure Toolkit":segment==="College"?"College Transition":"Workday Wellbeing"} p="Structured, stage-aware support." icon={<ClipboardList/>} go={()=>go("programs")}/><Tile t="Exercises" p="Short guided activities." icon={<Sparkles/>} go={()=>go("exercises")}/><Tile t="Your progress" p="Patterns and actions—not a score." icon={<BarChart3/>} go={()=>go("progress")}/></div>
 <div className="privacy"><LockKeyhole/><div><b>Your private space stays private.</b><p>Journals and personal AI conversations are separate from institution-level reporting.</p></div><button onClick={()=>go("privacy")}>Learn more</button></div></div>}
function Action({icon,t,s,go}:any){return <button className="action" onClick={go}><span>{icon}</span><div><b>{t}</b><small>{s}</small></div><ChevronRight/></button>}
function Tile({icon,t,p,go}:any){return <button className="tile" onClick={go}><span>{icon}</span><h3>{t}</h3><p>{p}</p><ChevronRight/></button>}
function Checkin({mood,setMood,stress,setStress,save}:any){const [energy,setEnergy]=useState("Medium"),[need,setNeed]=useState("");return <div className="page narrow"><Title ey="CHECK-IN" title="Understand the moment you’re in" sub="This is for you. You can skip any question."/><div className="card form"><h3>How are you feeling?</h3><div className="moods large">{["Good","Okay","Low","Stressed","Frustrated","Tired"].map(x=><button className={mood===x?"chosen":""} onClick={()=>setMood(x)} key={x}>{x}</button>)}</div><Metric t="Stress" v={stress} set={setStress}/><Choices t="Energy" a={["Low","Medium","High"]} v={energy} set={setEnergy}/><Choices t="What do you need?" a={["Calm","Focus","Plan","Reflect","Talk","Learn"]} v={need} set={setNeed}/><div className="actions"><button className="secondary" onClick={save}>Skip</button><button className="primary" onClick={save}>Save check-in <ChevronRight size={15}/></button></div></div></div>}
function Metric({t,v,set}:any){return <div className="metric"><div><b>{t}</b><strong>{v}/10</strong></div><input type="range" min="0" max="10" value={v} onChange={e=>set(+e.target.value)}/></div>}
function Choices({t,a,v,set}:any){return <div className="choices"><b>{t}</b><div>{a.map((x:string)=><button key={x} className={v===x?"chosen":""} onClick={()=>set(x)}>{x}</button>)}</div></div>}
function Journal({value,setValue,entries,save}:any){return <div className="page"><Title ey="PRIVATE JOURNAL" title="A space to put things down." sub="Your journal is private. Institution dashboards do not receive the entry text."/><div className="journal"><div className="card editor"><textarea value={value} onChange={e=>setValue(e.target.value)} placeholder="What’s on your mind?"/><div className="editorfoot"><span>Private entry</span><button className="primary" onClick={save}>Save entry</button></div></div><div className="card history"><h3>Recent entries</h3>{entries.length?entries.map((e:string,i:number)=><div className="entry" key={i}><small>Saved privately</small><p>{e}</p></div>):<div className="empty">Your saved entries will appear here.</div>}</div></div></div>}
function Goals({value,setValue,goals,add}:any){return <div className="page"><Title ey="GOALS" title="Keep one meaningful thing moving." sub="Goals are personal and visible only in your private space."/><div className="goaladd"><Target/><input value={value} onChange={e=>setValue(e.target.value)} onKeyDown={e=>e.key==="Enter"&&add()} placeholder="Add a goal…"/><button className="primary" onClick={add}>Add goal</button></div><div className="goallist">{goals.length?goals.map((g:string,i:number)=><div className="card goal" key={i}><i/><div><small>ACTIVE GOAL</small><h3>{g}</h3><p>Choose one next action today.</p></div><ChevronRight/></div>):<div className="empty">No goals yet. Start with one small, concrete goal.</div>}</div></div>}
function Exercises({active,setActive,step,setStep,done}:any){if(active!==null){const e=exercises[active];return <div className="page narrow"><button className="back" onClick={()=>{setActive(null);setStep(0)}}>← Back to exercises</button><div className="exercise-run"><div className="bigicon">{e[0]}</div><small>GUIDED EXERCISE • {e[3]}</small><h1>{e[1]}</h1><p>{e[4]}</p><div className="bar"><i style={{width:`${((step+1)/3)*100}%`}}/></div><div className="step"><small>STEP {step+1} OF 3</small><h2>{step===0?"Name what is happening":step===1?"Choose one thing you can control":"Write your next tiny action"}</h2><textarea placeholder="Type a few words…"/><button className="primary" onClick={()=>step<2?setStep(step+1):done()}>{step<2?"Continue":"Complete exercise"} <ChevronRight size={15}/></button></div></div></div>}
 return <div className="page"><Title ey="EXERCISES" title="Small tools for real moments." sub="Choose a guided activity based on what you need right now."/><div className="exgrid">{exercises.map((e,i)=><button className="excard" key={i} onClick={()=>setActive(i)}><span className="exicon">{e[0]}</span><small>{e[3]}</small><em>{e[2]}</em><h3>{e[1]}</h3><p>{e[4]}</p><footer>Guided activity <ChevronRight size={13}/></footer></button>)}</div></div>}
function Programs({segment,notify}:any){return <div className="page"><Title ey="PROGRAMS" title={`${segment} wellbeing programs`} sub="Structured content that can be offered individually or through an institution."/><div className="programs">{programs.map((p,i)=><div className="card program" key={i}><div className="cover"><b>{p[0]}</b><Sparkles/></div><div className="pbody"><small>{p[1]} • {p[2]}</small><p>Short lessons, activities and reflection prompts designed for this stage.</p><button onClick={()=>notify("Program preview opened")}>Preview →</button></div></div>)}</div></div>}
function Progress(){return <div className="page"><Title ey="PROGRESS" title="Notice patterns, not scores." sub="Your personal progress view focuses on actions and reflections."/><div className="stats"><div className="card stat"><strong>12</strong><b>check-ins</b><small>this month</small></div><div className="card stat"><strong>7</strong><b>exercises</b><small>completed</small></div><div className="card stat"><strong>4</strong><b>goals</b><small>started</small></div><div className="card stat"><strong>6</strong><b>active days</b><small>last 14 days</small></div></div><div className="progressgrid"><div className="card chart"><small>RECENT ACTIVITY</small><h2>Small actions add up</h2><div className="bars">{[35,52,44,72,60,84,67].map((h,i)=><div key={i}><span style={{height:`${h}%`}}><b>{Math.round(h/10)}</b></span><small>{["M","T","W","T","F","S","S"][i]}</small></div>)}</div></div><div className="insight"><small>AAVYA INSIGHT</small><h3>You’ve been using short exercises more consistently.</h3><p>Keep choosing tools that fit the moment rather than trying to do everything at once.</p></div></div></div>}
function AI({messages,input,setInput,send}:any){return <div className="page narrow"><Title ey="AAVYA AI" title="A calm place to think out loud." sub="AAVYA can support reflection and planning. It does not diagnose or replace professional care."/><div className="card ai"><div className="aihead"><span><MessageCircleHeart/></span><div><b>AAVYA</b><small>Personal wellbeing assistant</small></div></div><div className="messages">{messages.map((m:any,i:number)=><div key={i} className={`msg ${m.role}` }><span>{m.role==="ai"?"A":"You"}</span><p>{m.text}</p></div>)}</div><div className="suggestions"><button onClick={()=>setInput("I’m stressed about exams")}>Exam stress</button><button onClick={()=>setInput("Help me plan my day")}>Plan my day</button><button onClick={()=>setInput("Give me a calming exercise")}>Calm me down</button></div><div className="aibox"><input value={input} onChange={e=>setInput(e.target.value)} onKeyDown={e=>e.key==="Enter"&&send()} placeholder="Write to AAVYA…"/><button onClick={send}>→</button></div></div></div>}
function Support({segment}:any){return <div className="page"><Title ey="SUPPORT" title="You don’t have to handle everything alone." sub={`Support options for the ${segment.toLowerCase()} experience.`}/><div className="supportgrid"><div className="card support"><Users/><h3>Trusted people</h3><p>Identify a parent, friend, teacher, mentor, manager or another person you trust.</p></div><div className="card support"><HeartHandshake/><h3>Professional support</h3><p>When you need more than a self-guided tool, consider a qualified mental-health professional.</p></div><div className="card support"><BriefcaseBusiness/><h3>Institution support</h3><p>Schools, colleges and workplaces can provide their own support pathways and contacts.</p></div><div className="card support"><GraduationCap/><h3>Urgent help</h3><p>If you may be in immediate danger or unable to stay safe, contact local emergency services or a trusted person now.</p></div></div></div>}
function Privacy(){return <div className="page"><Title ey="PRIVACY & DATA" title="Your private space, clearly separated." sub="The product should keep personal content distinct from institution-level wellbeing insights."/><div className="privacygrid"><div className="card pcard"><LockKeyhole/><h3>Private by default</h3><p>Journal text, personal goals and individual AI conversations belong in the private user space.</p></div><div className="card pcard"><BarChart3/><h3>Aggregate institution insights</h3><p>Institution dashboards should use de-identified or aggregate reporting rather than exposing personal entries.</p></div><div className="card pcard"><Users/><h3>Role-based access</h3><p>Student, educator, counsellor, HR and administrator permissions should be explicitly separated.</p></div><div className="card pcard"><LockKeyhole/><h3>Future production requirements</h3><p>Authentication, consent, guardian workflows where applicable, tenant isolation, encryption, audit logs, retention controls and safety escalation must be implemented before real users.</p></div></div></div>}
